# Dockerfile.vite
FROM node:20-alpine

WORKDIR /app

# Use cache de deps do próprio Docker
COPY package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit

# Copia só o resto do código
COPY . .

CMD ["npm","run","dev"]
